# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: create file
        run: |
          echo XXX > output
      - uses: popsiclestick/gist-sync-action@v1.1.0
        id: sync
        with:
          auth: ${{ secrets.TD }}
          gist_url: https://gist.github.com/RCmerci/10f9f945f225e4340e3cd31c5c051088
          gist_title: tdbooster-output
          gist_description: Example Gist Description
          github_file: output      
