# This is a basic workflow to help you get started with Actions

name: build-and-run

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 9 * * 1-5"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up OCaml
        # You may pin to the exact commit or the version.
        # uses: avsm/setup-ocaml@a4c3fb2490fe41b448c5e7bbaa446d79e87e0ee7
        uses: avsm/setup-ocaml@v1
        with:
          # Version of the OCaml compiler to initialise
          ocaml-version: 4.10.1

      - name: install dependencies
        run: opam install . --deps-only --with-doc --with-test

      # Runs a set of commands using the runners shell
      - name: build
        run: |
          opam exec -- dune build
          opam exec -- dune build @web/default
          make web
      
      - name: upload-bin
        uses: actions/upload-artifact@v2.2.0
        with:
          name: tdbooster.exe
          path: _build/default/tdbooster.exe
          
      - name: sync main-js gist
        uses: Popsiclestick/gist-sync-action@v1.1
        with:
          auth: ${{ secrets.TD }}
          gist_url: https://gist.github.com/RCmerci/58a81f8ebff751bc99b68904531ce138
          gist_title: main.js
          gist_description: main.js
          github_file: main.js

  run:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.x

      - name: install python dependencies
        run: pip install pandas baostock
          
      - name: download-bin
        uses: actions/download-artifact@v2.0.5
        with:
          name: tdbooster.exe

      - name: run
        run: |
          chmod +x ./tdbooster.exe
          ./tdbooster.exe -r -o .  -f sz.300015 -f sh.600000 -f sh.600703 -f sh.600547 -f sh.600009 -f sz.000895 -f sh.600900 -f sh.601318 -f sh.600690 -f sh.601012 -f sz.300498 -f sz.002304 -f sz.001979 -f sz.000063 -f sh.603160 -f sh.601888 -f sz.000725 -f sh.600048 -f sh.600585 -f sh.601601 -f sh.600104 -f sz.002475 -f sh.601088 -f sz.000002 -f sh.603288 -f sz.002415 -f sz.000651 -f sh.600276 -f sh.600028 -f sz.000858 -f sh.601628 -f sh.600036 -f sh.600519 -f sz.000333 -f sh.600031 -f sh.600030 > output

      - name: db
        uses: actions/upload-artifact@v2.2.0
        with:
          name: tdbooster.db
          path: tdbooster.db
          
      - name: sync gist
        uses: Popsiclestick/gist-sync-action@v1.1
        with:
          auth: ${{ secrets.TD }}
          gist_url: https://gist.github.com/RCmerci/10f9f945f225e4340e3cd31c5c051088
          gist_title: tdbooster-output
          gist_description: tdbooster output
          github_file: output  
